# Generated by Django 4.1 on 2023-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messege_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_user', models.CharField(max_length=250)),
                ('messege', models.CharField(max_length=1000)),
                ('m_time', models.DateTimeField(blank=True, null=True)),
                ('m_room', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='room_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=500)),
                ('reffer_code', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
            ],
        ),
    ]
